[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor_nft = "53WyXS6dXWbtwNtAjamoP7NoAe3dx4ki8XuJ5vuZmSB6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
